name: Documentation Builder

on:
  push:
    paths:
      - '.github/workflows/docs.yml'
      - 'lua/**'
      - 'src/docs/**'
    branches:
      - main

jobs:
  docs:
    name: Build Docs
    runs-on: ubuntu-latest

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download LDoc
        uses: actions/checkout@v3
        with:
          path: src/docs/ldoc
          repository: limelight-development/LDoc
      - name: Download Template
        uses: actions/checkout@v3
        with:
          path: src/docs/template
          repository: limelight-development/documentation-template
      - name: Build
        run: ./src/docs/build.sh
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./src/docs/build/
          publish_branch: gh-pages
